/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Profile new color palette
        "on-tertiary-container": "#65bbb1",
        "on-surface-variant": "#44474c",
        "surface-container-low": "#fbf2ed",
        "primary-container": "#334155",
        "tertiary-fixed": "#9cf2e8",
        "surface-tint": "#515f74",
        "on-primary-fixed-variant": "#3a485c",
        "surface-dim": "#e1d8d4",
        "on-secondary-container": "#54647a",
        "on-tertiary-fixed-variant": "#00504a",
        "secondary-fixed": "#d3e4fe",
        "surface-bright": "#fff8f5",
        "on-secondary-fixed-variant": "#38485d",
        "error": "#ba1a1a",
        "surface-variant": "#eae1dc",
        "inverse-primary": "#b9c7e0",
        "primary-fixed": "#d5e3fd",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#0d1c2f",
        "secondary-container": "#d0e1fb",
        "inverse-on-surface": "#f8efeb",
        "tertiary-container": "#004944",
        "on-error": "#ffffff",
        "on-surface": "#1f1b18",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#80d5cb",
        "outline-variant": "#c5c6cd",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container": "#f6ece8",
        "outline": "#75777d",
        "on-secondary-fixed": "#0b1c30",
        "on-error-container": "#93000a",
        "on-background": "#1f1b18",
        "on-tertiary-fixed": "#00201d",
        "surface-container-high": "#f0e6e2",
        "primary-fixed-dim": "#b9c7e0",
        "tertiary": "#00312d",
        "surface-container-highest": "#eae1dc",
        "surface": "#fff8f5",
        "on-primary-container": "#9eadc5",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#342f2d",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}